/**
 * schema.ts — RDD SQLite Schema Definition
 *
 * SQL DDL constants and TypeScript type definitions for all three tables:
 *   - conversations: one thread per legal case (causa_id)
 *   - messages: individual turns in each conversation
 *   - audit_log: append-only change trail
 *
 * SQL is written with IF NOT EXISTS so initialization is idempotent.
 * Copy SQL constants directly from schema-spec.md — do not modify.
 */

// ─────────────────────────────────────────────────────────────────────────────
// SQL DDL Constants
// ─────────────────────────────────────────────────────────────────────────────

export const CONVERSATIONS_TABLE = `
CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY NOT NULL,
  causa_id TEXT UNIQUE NOT NULL,
  metadata JSON NOT NULL DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP,
  CHECK(
    typeof(id) = 'text' AND length(id) > 0 AND
    typeof(causa_id) = 'text' AND length(causa_id) > 0
  )
);
`.trim();

export const MESSAGES_TABLE = `
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY NOT NULL,
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  metadata JSON NOT NULL DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CHECK(
    typeof(role) = 'text' AND role IN ('user', 'assistant') AND
    typeof(content) = 'text' AND length(content) > 0 AND
    typeof(id) = 'text' AND length(id) > 0
  )
);
`.trim();

export const AUDIT_LOG_TABLE = `
CREATE TABLE IF NOT EXISTS audit_log (
  id TEXT PRIMARY KEY NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  user_id TEXT NOT NULL,
  changes JSON NOT NULL,
  metadata JSON NOT NULL DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK(
    typeof(entity_type) = 'text' AND
      entity_type IN ('conversation', 'message') AND
    typeof(action) = 'text' AND
      action IN ('CREATE', 'UPDATE', 'CLOSE') AND
    typeof(user_id) = 'text' AND length(user_id) > 0 AND
    typeof(id) = 'text' AND length(id) > 0
  )
);
`.trim();

/** All 5 indexes — conversations (3) + messages (4 collapsed to 4) + audit_log (5). */
export const ALL_INDEXES = `
CREATE INDEX IF NOT EXISTS idx_conversations_causa_id ON conversations(causa_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations(created_at);
CREATE INDEX IF NOT EXISTS idx_conversations_closed_at ON conversations(closed_at);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_role ON messages(role);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created ON messages(conversation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity_id ON audit_log(entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity_type_created ON audit_log(entity_type, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);
`.trim();

/** Combined DDL: tables first, then indexes. Idempotent — safe to run on every startup. */
export const FULL_SCHEMA = `${CONVERSATIONS_TABLE}\n\n${MESSAGES_TABLE}\n\n${AUDIT_LOG_TABLE}\n\n${ALL_INDEXES}`;

// ─────────────────────────────────────────────────────────────────────────────
// Enum Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * MessageRole — who sent the message.
 * - 'user': input from admin/staff
 * - 'assistant': response generated by Claude (RDD agent)
 */
export type MessageRole = 'user' | 'assistant';

/**
 * AuditAction — what operation occurred.
 * - 'CREATE': new record inserted
 * - 'UPDATE': existing record modified
 * - 'CLOSE': case closure
 */
export type AuditAction = 'CREATE' | 'UPDATE' | 'CLOSE';

/**
 * AuditEntityType — which table was touched.
 * - 'conversation': conversations table modified
 * - 'message': messages table modified
 */
export type AuditEntityType = 'conversation' | 'message';

// ─────────────────────────────────────────────────────────────────────────────
// Conversation Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ConversationMetadata — JSON shape stored in conversations.metadata.
 * Fields from webhook arrive at CREATE time; parsed fields are added later.
 */
export interface ConversationMetadata {
  /** From webhook: defendant name */
  demandado?: string;

  /** From webhook: plaintiff claim amount (in pesos) */
  monto_demanda?: number;

  /** From webhook: court name */
  tribunal?: string;

  /** From webhook: RIT number */
  rit?: string;

  /** From webhook: case stage (e.g., "litigacion", "cobranza") */
  etapa?: string;

  /** Parsed in conversation: registered settlement amount */
  acuerdo_monto?: number;

  /** Parsed in conversation: payment installment count */
  acuerdo_cuotas?: number;

  /** Parsed in conversation: lawyer handling closure */
  abogado_nombre?: string;

  /** Parsed in conversation: lawyer email */
  abogado_email?: string;

  /** System: canonical case state */
  case_state?: 'litigacion' | 'cobranza' | 'archivado';

  /** System: total number of messages in this conversation */
  message_count?: number;

  /** Drive: root folder ID created on causa-nueva */
  drive_folder_id?: string;
}

/**
 * Conversation — one conversation thread per legal case (causa_id).
 * Created when webhook arrives; closed when case finalizes.
 */
export interface Conversation {
  /** Unique conversation ID (UUID v4) */
  id: string;

  /** Case reference from webhook (e.g., "2024-00123") */
  causa_id: string;

  /** Case metadata from webhook and runtime state */
  metadata: ConversationMetadata;

  /** When conversation was created (webhook received) */
  created_at: Date;

  /** Last time conversation was modified */
  updated_at: Date;

  /** When case was closed; null if still active */
  closed_at: Date | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Message Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * MessageMetadata — JSON shape stored in messages.metadata.
 * User messages: parsed intent + extracted values.
 * Assistant messages: response strategy, confidence, flags.
 */
export interface MessageMetadata {
  /** For user messages: detected intent */
  intent?: 'acuerdo' | 'pago' | 'cierre' | 'consulta' | 'otro';

  /** For user messages: extracted monto (in pesos) */
  monto_extraido?: number;

  /** For user messages: extracted cuotas count */
  cuotas_extraido?: number;

  /** For user messages: extracted date string (ISO) */
  fecha_extraida?: string;

  /** For assistant messages: response type */
  response_type?: 'confirmation' | 'ask_for_clarification' | 'error' | 'summary';

  /** For assistant messages: whether processing succeeded */
  processing_ok?: boolean;

  /** For assistant messages: warning flags */
  flags?: string[];

  /** System: Claude model ID used (if assistant message) */
  model?: string;

  /** System: token usage (if assistant message) */
  tokens_used?: {
    input: number;
    output: number;
  };
}

/**
 * Message — one turn in a conversation.
 * Immutable after creation. Sent by 'user' or 'assistant'.
 */
export interface Message {
  /** Unique message ID (UUID v4) */
  id: string;

  /** Which conversation this message belongs to */
  conversation_id: string;

  /** Who sent: 'user' or 'assistant' */
  role: MessageRole;

  /** Message text (user input or Claude response) */
  content: string;

  /** Parsed intent and extracted data (or response strategy) */
  metadata: MessageMetadata;

  /** When message was created */
  created_at: Date;
}

// ─────────────────────────────────────────────────────────────────────────────
// Audit Log Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * AuditChanges — before/after values for every modified field.
 * Example: { "metadata.acuerdo_monto": { before: null, after: 1800000 } }
 */
export type AuditChanges = Record<string, {
  before: unknown;
  after: unknown;
}>;

/**
 * AuditMetadata — context for why a change happened.
 */
export interface AuditMetadata {
  /** How the change was triggered */
  trigger?: 'webhook' | 'manual_user' | 'system';

  /** Which webhook type triggered the change (if trigger = 'webhook') */
  webhook_type?: 'CREACION' | 'CIERRE' | 'ACTUALIZACION';

  /** IP address of requester (if manual) */
  ip_address?: string;

  /** User agent string (if manual) */
  user_agent?: string;

  /** Free-form notes about the change */
  notes?: string;
}

/**
 * AuditLogEntry — immutable audit trail record.
 * Every write to conversations/messages is logged here.
 * Append-only: never updated, never deleted.
 */
export interface AuditLogEntry {
  /** Unique audit entry ID (UUID v4) */
  id: string;

  /** Which entity type was modified */
  entity_type: AuditEntityType;

  /** ID of the entity that was modified */
  entity_id: string;

  /** What operation occurred */
  action: AuditAction;

  /** Who triggered the change (e.g., "webhook_sistema", "admin_12345") */
  user_id: string;

  /** Field-level before/after values */
  changes: AuditChanges;

  /** Additional context (trigger, IP, notes) */
  metadata: AuditMetadata;

  /** When the change occurred */
  created_at: Date;
}
